-- LOCAL_CONFIG_GET_VALUE_FOR_KEY_X
"SELECT " + COLUMN_LOCAL_CONFIG_VALUE + " " +
"FROM " + TABLE_LOCAL_CONFIG + " " +
"WHERE " + COLUMN_LOCAL_CONFIG_KEY + " = ?; " 

-- MNEMOSYNE_V5_INSERT_LOCAL_CONFIG_KEY_VALUE_X_Y
"INSERT OR IGNORE INTO " + TABLE_LOCAL_CONFIG + " " +
"	(" + COLUMN_LOCAL_CONFIG_KEY + ", " + COLUMN_LOCAL_CONFIG_VALUE + ") " +
"VALUES " +
"	(?, ?); " 

-- MNEMOSYNE_V5_UPDATE_LOCAL_CONFIG_VALUE_FOR_KEY_X_Y
"UPDATE " + TABLE_LOCAL_CONFIG + " " +
"SET " + COLUMN_LOCAL_CONFIG_VALUE + " = ? " +
"WHERE " + COLUMN_LOCAL_CONFIG_KEY + " = ?; " 