-- SYNERGY_V5_SELECT_ACTIVE_LISTS
"SELECT " + COLUMN_SYNERGY_LIST_NAME + " "
+ "FROM " + TABLE_SYNERGY_LIST + " "
+ "WHERE " + COLUMN_SYNERGY_LIST_SHELVED_AT + " IS NULL "
+ "   OR " + COLUMN_SYNERGY_LIST_ACTIVATED_AT + " >= " + COLUMN_SYNERGY_LIST_SHELVED_AT + " "
+ "ORDER BY " + COLUMN_SYNERGY_LIST_NAME + "; "

-- SYNERGY_V5_SELECT_SHELVED_LISTS
"SELECT " + COLUMN_SYNERGY_LIST_NAME + " "
+ "FROM " + TABLE_SYNERGY_LIST + " "
+ "WHERE " + COLUMN_SYNERGY_LIST_ACTIVATED_AT + " < " + COLUMN_SYNERGY_LIST_SHELVED_AT + " "
+ "ORDER BY " + COLUMN_SYNERGY_LIST_NAME + "; "

-- SYNERGY_V5_ENSURE_LIST_NAME_X
"INSERT OR IGNORE INTO " + TABLE_SYNERGY_LIST + " "
+ "	(" + COLUMN_SYNERGY_LIST_NAME + ") "
+ "VALUES "
+ "	(?); "

-- SYNERGY_V5_SELECT_ID_FOR_LIST_NAME
"SELECT " + COLUMN_SYNERGY_LIST_ID + " "
+ "FROM " + TABLE_SYNERGY_LIST + " "
+ "WHERE " + COLUMN_SYNERGY_LIST_NAME + " = ? ;"

-- SYNERGY_V5_SELECT_ID_ACTIVATED_AT_SHELVED_AT_FOR_LIST_NAME
"SELECT " + COLUMN_SYNERGY_LIST_ID + ", "
	   	  + COLUMN_SYNERGY_LIST_ACTIVATED_AT + ", "
	   	  + COLUMN_SYNERGY_LIST_SHELVED_AT + " "
+ "FROM " + TABLE_SYNERGY_LIST + " "
+ "WHERE " + COLUMN_SYNERGY_LIST_NAME + " = ? ;"

-- SYNERGY_V5_ENSURE_ITEM_VALUE_X
"INSERT OR IGNORE INTO " + TABLE_SYNERGY_ITEM + " "
+ "	(" + COLUMN_SYNERGY_ITEM_VALUE + ") "
+ "VALUES "
+ "	(?); "

-- SYNERGY_V5_SELECT_ID_FOR_ITEM_VALUE
"SELECT " + COLUMN_SYNERGY_ITEM_ID + " "
+ "FROM " + TABLE_SYNERGY_ITEM + " "
+ "WHERE " + COLUMN_SYNERGY_ITEM_VALUE + " = ? ; "

-- SYNERGY_V5_SELECT_LIST_ITEM_ID_FOR_LIST_ID_ITEM_ID_X_Y
"SELECT " + COLUMN_SYNERGY_LIST_ITEM_ID + " "
+ "FROM " + TABLE_SYNERGY_LIST_ITEM + " "
+ "WHERE " + COLUMN_SYNERGY_LIST_ID + " = ?  "
+ "AND " + COLUMN_SYNERGY_ITEM_ID + " = ? ; "

-- SYNERGY_V5_ENSURE_LIST_ITEM_POSITION_X_Y_Z
"INSERT OR IGNORE INTO " + TABLE_SYNERGY_LIST_ITEM + " "
+ "	(" + COLUMN_SYNERGY_LIST_ID + ",  "
+ "	 " + COLUMN_SYNERGY_ITEM_ID + ",  "
+ "	 " + COLUMN_SYNERGY_LIST_ITEM_POSITION +  ") "
+ "VALUES "
+ "	(?, ?, ?); "

-- SYNERGY_V5_SELECT_ITEM_VALUES_BY_POSITION_FOR_LIST_ID_X
"SELECT si." + COLUMN_SYNERGY_ITEM_ID + ", "
+ "	    si." + COLUMN_SYNERGY_ITEM_VALUE + ", "
+ "	    sli." + COLUMN_SYNERGY_LIST_ITEM_POSITION + " "
+ "FROM " + TABLE_SYNERGY_LIST_ITEM + " sli "
+ "JOIN " + TABLE_SYNERGY_ITEM + " si "
+ "ON sli." + COLUMN_SYNERGY_ITEM_ID + " = si." + COLUMN_SYNERGY_ITEM_ID + " "
+ "WHERE sli." + COLUMN_SYNERGY_LIST_ID + " = ? ; "

-- SYNERGY_V5_SELECT_LIST_ITEMS_AND_TODOS_BY_POSITION_FOR_LIST_ID_X
"SELECT si." + COLUMN_SYNERGY_ITEM_ID + ", "
+ "	    si." + COLUMN_SYNERGY_ITEM_VALUE + ", "
+ "	    sli." + COLUMN_SYNERGY_LIST_ITEM_POSITION + ", "
+ "     sli." + COLUMN_SYNERGY_LIST_ITEM_ID + ", "
+ "     std." + COLUMN_SYNERGY_TO_DO_ID + ", "
+ "     std." + COLUMN_SYNERGY_TO_DO_ACTIVATED_AT + ", "
+ "     std." + COLUMN_SYNERGY_TO_DO_COMPLETED_AT + ", "
+ "     std." +COLUMN_SYNERGY_TO_DO_ARCHIVED_AT + " "
+ "FROM " + TABLE_SYNERGY_LIST_ITEM + " sli "
+ "JOIN " + TABLE_SYNERGY_ITEM + " si "
+ "ON sli." + COLUMN_SYNERGY_ITEM_ID + " = si." + COLUMN_SYNERGY_ITEM_ID + " "
+ "LEFT JOIN " + TABLE_SYNERGY_TO_DO + " std "
+ "ON sli." + COLUMN_SYNERGY_LIST_ITEM_ID + " = std." + COLUMN_SYNERGY_LIST_ITEM_ID + " "
+ "WHERE sli." + COLUMN_SYNERGY_LIST_ID + " = ? "
+   "ORDER BY sli." + COLUMN_SYNERGY_LIST_ITEM_POSITION + "; "

-- SYNERGY_V5_LIST_UPDATE_ACTIVATE_AT_SHELVED_AT_FOR_LIST_NAME_X_Y_Z
"UPDATE " + TABLE_SYNERGY_LIST + " "
+ "SET " + COLUMN_SYNERGY_LIST_ACTIVATED_AT + " = MAX(IFNULL(" + COLUMN_SYNERGY_LIST_ACTIVATED_AT + ", ''), ?), "
+ "	   " + COLUMN_SYNERGY_LIST_SHELVED_AT + " = MAX(IFNULL(" + COLUMN_SYNERGY_LIST_SHELVED_AT + ", ''), ?) "
+ "WHERE " + COLUMN_SYNERGY_LIST_NAME + " = ?; "

-- SYNERGY_V5_UPDATE_POSITION_FOR_LIST_ITEM_ID_X_Y
"UPDATE " + TABLE_SYNERGY_LIST_ITEM + " "
+ "SET " + COLUMN_SYNERGY_LIST_ITEM_POSITION + " = ? "
+ "WHERE " + COLUMN_SYNERGY_LIST_ITEM_ID + " = ? ; "

-- SYNERGY_V5_ENSURE_TO_DO_FOR_LIST_ITEM_ID_ID_AC_CO_AR
"INSERT OR IGNORE INTO " + TABLE_SYNERGY_TO_DO + "  "
+ "	(" + COLUMN_SYNERGY_LIST_ITEM_ID + ", "
+ "	 " + COLUMN_SYNERGY_TO_DO_ACTIVATED_AT + ", "
+ "	 " + COLUMN_SYNERGY_TO_DO_COMPLETED_AT + ", "
+ "	 " + COLUMN_SYNERGY_TO_DO_ARCHIVED_AT + ")  "
+ "VALUES  "
+ "	(?, ?, ?, ?); "

-- SYNERGY_V5_UPDATE_TO_DO_WHERE_LIST_ITEM_ID_AC_CO_AR_ID "
"UPDATE " + TABLE_SYNERGY_TO_DO + "  "
+ "SET " + COLUMN_SYNERGY_TO_DO_ACTIVATED_AT + " = MAX(IFNULL(" + COLUMN_SYNERGY_TO_DO_ACTIVATED_AT + ", ''), ?), "
+ "	   " + COLUMN_SYNERGY_TO_DO_COMPLETED_AT + " = MAX(IFNULL(" + COLUMN_SYNERGY_TO_DO_COMPLETED_AT + ", ''), ?), "
+ "	   " + COLUMN_SYNERGY_TO_DO_ARCHIVED_AT + " = MAX(IFNULL(" + COLUMN_SYNERGY_TO_DO_ARCHIVED_AT + ", ''), ?) "
+ "WHERE " + COLUMN_SYNERGY_LIST_ITEM_ID + " = ?; "

-- SYNERGY_V5_SELECT_LIST_NAMES_WITH_ITEM_COUNTS
"SELECT sl." + COLUMN_SYNERGY_LIST_NAME + ", COUNT(sli." + COLUMN_SYNERGY_LIST_ITEM_ID + ") AS '" + COLUMN_COUNT + "' "
+ "FROM " + TABLE_SYNERGY_LIST + " sl "
+ "LEFT JOIN " + TABLE_SYNERGY_LIST_ITEM + " sli "
+ "ON sl." + COLUMN_SYNERGY_LIST_ID + " = sli." + COLUMN_SYNERGY_LIST_ID + " "
+ "LEFT JOIN " + TABLE_SYNERGY_TO_DO + " std "
+ "ON sli." + COLUMN_SYNERGY_LIST_ITEM_ID + " = std." + COLUMN_SYNERGY_LIST_ITEM_ID + " "
+ "WHERE (sl." + COLUMN_SYNERGY_LIST_SHELVED_AT + " IS NULL  "
+ "   OR sl." + COLUMN_SYNERGY_LIST_ACTIVATED_AT + " >= sl." + COLUMN_SYNERGY_LIST_SHELVED_AT + ") "
+ "AND (std." + COLUMN_SYNERGY_TO_DO_ID + " IS NULL  "
+ "	OR (std." + COLUMN_SYNERGY_TO_DO_ACTIVATED_AT + " >= std." + COLUMN_SYNERGY_TO_DO_COMPLETED_AT + " "
+ "		AND std." + COLUMN_SYNERGY_TO_DO_ACTIVATED_AT + " >= std." + COLUMN_SYNERGY_TO_DO_ARCHIVED_AT + ") "
+ "	) "
+ "GROUP BY sl." + COLUMN_SYNERGY_LIST_NAME + " "
+ "ORDER BY sl." + COLUMN_SYNERGY_LIST_NAME + "; "


-- SYNERGY_V5_SELECT_LIST_NAMES_WITH_ITEM_COUNTS_NEW =
"SELECT sl." + COLUMN_SYNERGY_LIST_NAME + ", SUM( " +
"	CASE  " +
"		WHEN std." + COLUMN_SYNERGY_TO_DO_ID + " IS NULL THEN 1 " +
"		WHEN std." + COLUMN_SYNERGY_TO_DO_ACTIVATED_AT + " >= std." + COLUMN_SYNERGY_TO_DO_COMPLETED_AT + " " +
"			AND std." + COLUMN_SYNERGY_TO_DO_ACTIVATED_AT + " >= std." + COLUMN_SYNERGY_TO_DO_ARCHIVED_AT + " " +
"		THEN 1 " +
"		ELSE 0 " +
"	END " +
") AS 'Count' " +
"FROM " + TABLE_SYNERGY_LIST + " sl " +
"LEFT JOIN " + TABLE_SYNERGY_LIST_ITEM + " sli " +
"ON sl." + COLUMN_SYNERGY_LIST_ID + " = sli." + COLUMN_SYNERGY_LIST_ID + " " +
"LEFT JOIN " + TABLE_SYNERGY_TO_DO + " std " +
"ON sli." + COLUMN_SYNERGY_LIST_ITEM_ID + " = std." + COLUMN_SYNERGY_LIST_ITEM_ID + " " +
"WHERE (sl." + COLUMN_SYNERGY_LIST_SHELVED_AT + " IS NULL  " +
"   OR sl." + COLUMN_SYNERGY_LIST_ACTIVATED_AT + " >= sl." + COLUMN_SYNERGY_LIST_SHELVED_AT + ") " +
"GROUP BY sl." + COLUMN_SYNERGY_LIST_NAME + " " +
"ORDER BY sl." + COLUMN_SYNERGY_LIST_NAME + "; "
