-- SYNERGY_V5_SELECT_ACTIVE_LISTS
"SELECT " + COLUMN_SYNERGY_LIST_NAME + " "
+ "FROM " + TABLE_SYNERGY_LIST + " "
+ "WHERE " + COLUMN_SYNERGY_LIST_SHELVED_AT + " IS NULL "
+ "   OR " + COLUMN_SYNERGY_LIST_ACTIVATED_AT + " > " + COLUMN_SYNERGY_LIST_SHELVED_AT + "; "

-- SYNERGY_V5_ENSURE_LIST_NAME_X
"INSERT OR IGNORE INTO " + TABLE_SYNERGY_LIST + " "
+ "	(" + COLUMN_SYNERGY_LIST_NAME + ") "
+ "VALUES "
+ "	(?); "

-- SYNERGY_V5_SELECT_ID_FOR_LIST_NAME
"SELECT " + COLUMN_SYNERGY_LIST_ID + " "
+ "FROM " + TABLE_SYNERGY_LIST + " "
+ "WHERE " + COLUMN_SYNERGY_LIST_NAME + " = ? ;"

-- SYNERGY_V5_SELECT_ID_ACTIVATED_AT_SHELVED_AT_FOR_LIST_NAME
"SELECT " + COLUMN_SYNERGY_LIST_ID + ", "
	   	  + COLUMN_SYNERGY_LIST_ACTIVATED_AT + ", "
	   	  + COLUMN_SYNERGY_LIST_SHELVED_AT + " "
+ "FROM " + TABLE_SYNERGY_LIST + " "
+ "WHERE " + COLUMN_SYNERGY_LIST_NAME + " = ? ;"

-- SYNERGY_V5_ENSURE_ITEM_VALUE_X
"INSERT OR IGNORE INTO " + TABLE_SYNERGY_ITEM + " "
+ "	(" + COLUMN_SYNERGY_ITEM_VALUE + ") "
+ "VALUES "
+ "	(?); "

-- SYNERGY_V5_SELECT_ID_FOR_ITEM_VALUE
"SELECT " + COLUMN_SYNERGY_ITEM_ID + " "
+ "FROM " + TABLE_SYNERGY_ITEM + " "
+ "WHERE " + COLUMN_SYNERGY_ITEM_VALUE + " = ? ; "

-- SYNERGY_V5_ENSURE_LIST_ITEM_POSITION_X_Y_Z
"INSERT OR IGNORE INTO " + TABLE_SYNERGY_LIST_ITEM + " "
+ "	(" + COLUMN_SYNERGY_LIST_ID + ",  "
+ "	 " + COLUMN_SYNERGY_ITEM_ID + ",  "
+ "	 " + COLUMN_SYNERGY_LIST_ITEM_POSITION +  ") "
+ "VALUES "
+ "	(?, ?, ?); "

-- SYNERGY_V5_SELECT_ITEM_VALUES_BY_POSITION_FOR_LIST_ID_X
"SELECT si." + COLUMN_SYNERGY_ITEM_ID + ", "
+ "	    si." + COLUMN_SYNERGY_ITEM_VALUE + ", "
+ "	    sli." + COLUMN_SYNERGY_LIST_ITEM_POSITION + " "
+ "FROM " + TABLE_SYNERGY_LIST_ITEM + " sli "
+ "JOIN " + TABLE_SYNERGY_ITEM + " si "
+ "ON sli." + COLUMN_SYNERGY_ITEM_ID + " = si." + COLUMN_SYNERGY_ITEM_ID + " "
+ "WHERE sli." + COLUMN_SYNERGY_LIST_ID + " = ? ; "