
-- CREATE_SOURCE_LOCATION
"CREATE TABLE " + TABLE_SOURCE_LOCATION + " ( " +
"	" + COLUMN_SOURCE_LOCATION_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_LOCATION_VALUE + " TEXT NOT NULL UNIQUE, " +
"	" + COLUMN_SOURCE_LOCATION_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_UPDATED_AT + " TEXT " +
") " 

-- CREATE_SOURCE_LOCATION_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_LOCATION + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_LOCATION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION + "." + COLUMN_SOURCE_LOCATION_ID + " = NEW." + COLUMN_SOURCE_LOCATION_ID + "; " +
"END " 

-- CREATE_SOURCE_LOCATION_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_LOCATION + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION + "." + COLUMN_SOURCE_LOCATION_ID + " = NEW." + COLUMN_SOURCE_LOCATION_ID + "; " +
"END " 







-- CREATE_SOURCE_ANNOTATION
"CREATE TABLE " + TABLE_SOURCE_ANNOTATION + " ( " +
"	" + COLUMN_SOURCE_ANNOTATION_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_ANNOTATION_VALUE + " TEXT NOT NULL UNIQUE, " +
"	" + COLUMN_SOURCE_ANNOTATION_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_ANNOTATION_UPDATED_AT + " TEXT " +
") " 

-- CREATE_SOURCE_ANNOTATION_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_ANNOTATION_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_ANNOTATION + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_ANNOTATION + "  " +
"	SET " + COLUMN_SOURCE_ANNOTATION_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_ANNOTATION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_ANNOTATION + "." + COLUMN_SOURCE_ANNOTATION_ID + " = NEW." + COLUMN_SOURCE_ANNOTATION_ID + "; " +
"END " 

-- CREATE_SOURCE_ANNOTATION_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_ANNOTATION_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_ANNOTATION + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_ANNOTATION + "  " +
"	SET " + COLUMN_SOURCE_ANNOTATION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_ANNOTATION + "." + COLUMN_SOURCE_ANNOTATION_ID + " = NEW." + COLUMN_SOURCE_ANNOTATION_ID + "; " +
"END " 






-- CREATE_SOURCE_TYPE
"CREATE TABLE " + TABLE_SOURCE_TYPE + " ( " +
"	" + COLUMN_SOURCE_TYPE_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_TYPE_VALUE + " TEXT NOT NULL UNIQUE, " +
"	" + COLUMN_SOURCE_TYPE_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_TYPE_UPDATED_AT + " TEXT " +
") " 

-- CREATE_SOURCE_TYPE_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_TYPE_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_TYPE + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_TYPE + "  " +
"	SET " + COLUMN_SOURCE_TYPE_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_TYPE_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_TYPE + "." + COLUMN_SOURCE_TYPE_ID + " = NEW." + COLUMN_SOURCE_TYPE_ID + "; " +
"END " 

-- CREATE_SOURCE_TYPE_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_TYPE_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_TYPE + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_TYPE + "  " +
"	SET " + COLUMN_SOURCE_TYPE_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_TYPE + "." + COLUMN_SOURCE_TYPE_ID + " = NEW." + COLUMN_SOURCE_TYPE_ID + "; " +
"END " 






-- CREATE_SOURCE
"CREATE TABLE " + TABLE_SOURCE + " ( " +
"	" + COLUMN_SOURCE_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_TYPE_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_TYPE + " (" + COLUMN_SOURCE_TYPE_ID + "), " +
"	" + COLUMN_SOURCE_AUTHOR + " TEXT, " +
"	" + COLUMN_SOURCE_DIRECTOR + " TEXT,  " +
"	" + COLUMN_SOURCE_TITLE + " TEXT,  " +
"	" + COLUMN_SOURCE_YEAR + " TEXT,  " +
"	" + COLUMN_SOURCE_URL + " TEXT,  " +
"	" + COLUMN_SOURCE_RETRIEVAL_DATE + " TEXT,  " +
"	" + COLUMN_SOURCE_TAG + " TEXT UNIQUE, " +
"	" + COLUMN_SOURCE_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_UPDATED_AT + " TEXT " +
") " 

-- CREATE_SOURCE_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE + "  " +
"	SET " + COLUMN_SOURCE_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE Source." + COLUMN_SOURCE_ID + " = NEW." + COLUMN_SOURCE_ID + "; " +
"END " 

-- CREATE_SOURCE_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE + "  " +
"	SET " + COLUMN_SOURCE_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE Source." + COLUMN_SOURCE_ID + " = NEW." + COLUMN_SOURCE_ID + "; " +
"END " 






-- CREATE_SOURCE_LOCATION_SUBSET
"CREATE TABLE " + TABLE_SOURCE_LOCATION_SUBSET + " ( " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_LOCATION_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_LOCATION + " (" + COLUMN_SOURCE_LOCATION_ID + "),  " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_VALUE + " TEXT NOT NULL, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_UPDATED_AT + " TEXT, " +
"	UNIQUE(" + COLUMN_SOURCE_LOCATION_ID + ", " + COLUMN_SOURCE_LOCATION_SUBSET_VALUE + ") " +
") " 

-- CREATE_SOURCE_LOCATION_SUBSET_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_SUBSET_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_LOCATION_SUBSET + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION_SUBSET + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_SUBSET_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_LOCATION_SUBSET_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION_SUBSET + "." + COLUMN_SOURCE_LOCATION_SUBSET_ID + " = NEW." + COLUMN_SOURCE_LOCATION_SUBSET_ID + "; " +
"END " 

-- CREATE_SOURCE_LOCATION_SUBSET_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_SUBSET_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_LOCATION_SUBSET + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION_SUBSET + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_SUBSET_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION_SUBSET + "." + COLUMN_SOURCE_LOCATION_SUBSET_ID + " = NEW." + COLUMN_SOURCE_LOCATION_SUBSET_ID + "; " +
"END " 






-- CREATE_SOURCE_LOCATION_SUBSET_ENTRY
"CREATE TABLE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + " ( " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_LOCATION_SUBSET + " (" + COLUMN_SOURCE_LOCATION_SUBSET_ID + "), " +
"	" + COLUMN_SOURCE_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE + " (" + COLUMN_SOURCE_ID + "),  " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_VALUE + " TEXT NOT NULL UNIQUE, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_VERIFIED_PRESENT_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_VERIFIED_MISSING_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_UPDATED_AT + " TEXT, " +
"	UNIQUE(" + COLUMN_SOURCE_LOCATION_SUBSET_ID + ", " + COLUMN_SOURCE_ID + ", " + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_VALUE + ") " +
") " 

-- CREATE_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + "." + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + " = NEW." + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + "; " +
"END " 

-- CREATE_SOURCE_LOCATION_SUBSET_ENTRY_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + "." + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + " = NEW." + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + "; " +
"END " 






-- CREATE_SOURCE_EXCERPT
"CREATE TABLE " + TABLE_SOURCE_EXCERPT + " ( " + 
"	" + COLUMN_SOURCE_EXCERPT_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " + 
"	" + COLUMN_SOURCE_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE + " (" + COLUMN_SOURCE_ID + "), " + 
"	" + COLUMN_SOURCE_EXCERPT_VALUE + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_PAGES + " TEXT,  " + 
"	" + COLUMN_SOURCE_EXCERPT_BEGIN_TIME + " TEXT,  " + 
"	" + COLUMN_SOURCE_EXCERPT_END_TIME + " TEXT,  " + 
"	" + COLUMN_SOURCE_EXCERPT_CREATED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_UPDATED_AT + " TEXT " + 
") " 

-- CREATE_SOURCE_EXCERPT_CREATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_CREATED_AT + "  " + 
"AFTER INSERT ON " + TABLE_SOURCE_EXCERPT + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_CREATED_AT + " = CURRENT_TIMESTAMP,  " + 
"		   " + COLUMN_SOURCE_EXCERPT_UPDATED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT + "." + COLUMN_SOURCE_EXCERPT_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_ID + "; " + 
"END " 

-- CREATE_SOURCE_EXCERPT_UPDATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_UPDATED_AT + " " + 
"AFTER UPDATE ON " + TABLE_SOURCE_EXCERPT + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_UPDATED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT + "." + COLUMN_SOURCE_EXCERPT_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_ID + "; " + 
"END " 






-- CREATE_SOURCE_EXCERPT_ANNOTATION 
"CREATE TABLE " + TABLE_SOURCE_EXCERPT_ANNOTATION + " ( " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " + 
"	" + COLUMN_SOURCE_EXCERPT_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_EXCERPT + " (" + COLUMN_SOURCE_EXCERPT_ID + "),  " + 
"	" + COLUMN_SOURCE_ANNOTATION_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_ANNOTATION + " (" + COLUMN_SOURCE_ANNOTATION_ID + "), " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_LINKED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_UNLINKED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_CREATED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_UPDATED_AT + " TEXT,  " + 
"	UNIQUE(" + COLUMN_SOURCE_EXCERPT_ID + ", " + COLUMN_SOURCE_ANNOTATION_ID + ") " + 
") " 

-- CREATE_SOURCE_EXCERPT_ANNOTATION_CREATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_ANNOTATION_CREATED_AT + "  " + 
"AFTER INSERT ON " + TABLE_SOURCE_EXCERPT_ANNOTATION + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT_ANNOTATION + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_ANNOTATION_CREATED_AT + " = CURRENT_TIMESTAMP,  " + 
"		   " + COLUMN_SOURCE_EXCERPT_ANNOTATION_UPDATED_AT + " = CURRENT_TIMESTAMP, " + 
"		   " + COLUMN_SOURCE_EXCERPT_ANNOTATION_LINKED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT_ANNOTATION + "." + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + "; " + 
"END " 

-- CREATE_SOURCE_EXCERPT_ANNOTATION_UPDATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_ANNOTATION_UPDATED_AT + " " + 
"AFTER UPDATE ON " + TABLE_SOURCE_EXCERPT_ANNOTATION + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT_ANNOTATION + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_ANNOTATION_UPDATED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT_ANNOTATION + "." + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + "; " + 
"END " 






-- CREATE_SOURCE_EXCERPT_TAGGING 
"CREATE TABLE " + TABLE_SOURCE_EXCERPT_TAGGING + " ( " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " + 
"	" + COLUMN_SOURCE_EXCERPT_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_EXCERPT + " (" + COLUMN_SOURCE_EXCERPT_ID + "),  " + 
"	" + COLUMN_MEDIA_TAG_ID + " INTEGER NOT NULL REFERENCES " + TABLE_MEDIA_TAG + " (" + COLUMN_MEDIA_TAG_ID + "), " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_TAGGED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_UNTAGGED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_CREATED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_UPDATED_AT + " TEXT,  " + 
"	UNIQUE(" + COLUMN_SOURCE_EXCERPT_ID + ", " + COLUMN_MEDIA_TAG_ID + ") " + 
") " 

-- CREATE_SOURCE_EXCERPT_TAGGING_CREATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_TAGGING_CREATED_AT + "  " + 
"AFTER INSERT ON " + TABLE_SOURCE_EXCERPT_TAGGING + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT_TAGGING + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_TAGGING_CREATED_AT + " = CURRENT_TIMESTAMP,  " + 
"		   " + COLUMN_SOURCE_EXCERPT_TAGGING_UPDATED_AT + " = CURRENT_TIMESTAMP, " + 
"		   " + COLUMN_SOURCE_EXCERPT_TAGGING_TAGGED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT_TAGGING + "." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + "; " + 
"END " 

-- CREATE_SOURCE_EXCERPT_TAGGING_UPDATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_TAGGING_UPDATED_AT + " " + 
"AFTER UPDATE ON " + TABLE_SOURCE_EXCERPT_TAGGING + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT_TAGGING + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_TAGGING_UPDATED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT_TAGGING + "." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + "; " + 
"END " 






