-- SELECT_TYPE_ID_TYPE_VALUE_FROM_SOURCE_TYPE
"SELECT " + NwdContract.COLUMN_SOURCE_TYPE_ID + ", " +
"	    " + NwdContract.COLUMN_SOURCE_TYPE_VALUE + " " +
"FROM " + NwdContract.TABLE_SOURCE_TYPE + "; "

-- SELECT_SOURCE_TYPE_ID_FOR_VALUE_X
"SELECT " + NwdContract.COLUMN_SOURCE_TYPE_ID + " " +
"FROM " + NwdContract.TABLE_SOURCE_TYPE + " " +
"WHERE " + NwdContract.COLUMN_SOURCE_TYPE_VALUE + " = ? ; " 

-- SELECT_SOURCE_EXCERPT_TYPE_ID_X_Y
"SELECT " + COLUMN_SOURCE_EXCERPT_ID + " " +
"FROM " + TABLE_SOURCE_EXCERPT + " " +
"WHERE " + COLUMN_SOURCE_ID + " = ? " +
"AND " + COLUMN_SOURCE_EXCERPT_VALUE + " = ? ; "

-- INSERT_OR_IGNORE_SOURCE_TYPE_VALUE
"INSERT OR IGNORE INTO " + NwdContract.TABLE_SOURCE_TYPE + " " +
"	(" + NwdContract.COLUMN_SOURCE_TYPE_VALUE + ") " +
"VALUES " +
"	(?); "

-- INSERT_OR_IGNORE_SOURCE_TYPE_VALUE
"INSERT OR IGNORE INTO " + TABLE_SOURCE_EXCERPT + " " + 
"	(" + COLUMN_SOURCE_ID + ", " + COLUMN_SOURCE_EXCERPT_VALUE + ") " + 
"VALUES " + 
"	(?, ?);"

-- SELECT_SOURCES_BY_TYPE_ID_X
"SELECT " + COLUMN_SOURCE_ID + ", " + 
"	   " + COLUMN_SOURCE_TYPE_ID + ", " + 
"	   " + COLUMN_SOURCE_TITLE + ", " + 
"	   " + COLUMN_SOURCE_AUTHOR + ", " + 
"	   " + COLUMN_SOURCE_DIRECTOR + ", " + 
"	   " + COLUMN_SOURCE_YEAR + ", " + 
"	   " + COLUMN_SOURCE_URL + ", " + 
"	   " + COLUMN_SOURCE_RETRIEVAL_DATE + "  " + 
"FROM " + TABLE_SOURCE + " " +
"WHERE " + COLUMN_SOURCE_TYPE_ID + " = ?; "

-- SELECT_SOURCE_W_X_Y_Z
"SELECT " + NwdContract.COLUMN_SOURCE_ID + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_TYPE_ID + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_TITLE + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_AUTHOR + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_DIRECTOR + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_YEAR + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_URL + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_RETRIEVAL_DATE + ",  " +
"	    " + NwdContract.COLUMN_SOURCE_TAG + "  " +
"FROM " + TABLE_SOURCE + " " +
"WHERE " + COLUMN_SOURCE_TYPE_ID + " = ?  " +
"AND TRIM(IFNULL(" + COLUMN_SOURCE_TITLE + ", '')) = TRIM(IFNULL(?, ''))  " +
"AND TRIM(IFNULL(" + COLUMN_SOURCE_YEAR + ", '')) = TRIM(IFNULL(?, ''))  " +
"AND TRIM(IFNULL(" + COLUMN_SOURCE_URL + ", '')) = TRIM(IFNULL(?, '')); " 

-- SELECT_SOURCE_BY_ID
"SELECT " + NwdContract.COLUMN_SOURCE_ID + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_TYPE_ID + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_TITLE + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_AUTHOR + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_DIRECTOR + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_YEAR + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_URL + ", " + 
"	    " + NwdContract.COLUMN_SOURCE_RETRIEVAL_DATE + ",  " +
"	    " + NwdContract.COLUMN_SOURCE_TAG + "  " +
"FROM " + TABLE_SOURCE + " " +
"WHERE " + COLUMN_SOURCE_ID + " = ? ; " 

-- INSERT_SOURCE_T_U_V_W_X_Y_Z
"INSERT OR IGNORE INTO " + TABLE_SOURCE + " " +
"	(" + COLUMN_SOURCE_TYPE_ID + ", " +
"	 " + COLUMN_SOURCE_TITLE + ", " +
"	 " + COLUMN_SOURCE_AUTHOR + ", " +
"	 " + COLUMN_SOURCE_DIRECTOR + ", " +
"	 " + COLUMN_SOURCE_YEAR + ", " +
"	 " + COLUMN_SOURCE_URL + ", " +
"	 " + COLUMN_SOURCE_RETRIEVAL_DATE + ") " +
"VALUES " +
"	(?,?,?,?,?,?,?); "

-- SELECT_EXCERPTS_WITH_TAGS_FOR_SOURCE_ID_X
"SELECT  sext." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + ", " +
"		se." + COLUMN_SOURCE_EXCERPT_ID + ", " +
"		se." + COLUMN_SOURCE_ID + ", " +
"		se." + COLUMN_SOURCE_EXCERPT_VALUE + ", " +
"		mt." + COLUMN_MEDIA_TAG_ID + ", " +
"		mt." + COLUMN_MEDIA_TAG_VALUE + " " +
"FROM " + TABLE_SOURCE_EXCERPT + " se " +
"LEFT JOIN " + TABLE_SOURCE_EXCERPT_TAGGING + " sext " +
"ON se." + COLUMN_SOURCE_EXCERPT_ID + " = sext." + COLUMN_SOURCE_EXCERPT_ID + " " +
"LEFT JOIN " + TABLE_MEDIA_TAG + " mt " +
"ON sext." + COLUMN_MEDIA_TAG_ID + " = mt." + COLUMN_MEDIA_TAG_ID + " " +
"WHERE se." + COLUMN_SOURCE_ID + " = ? ; " 

-- SELECT_EXCERPTS_WITH_TAGGED_TAGS_FOR_SOURCE_ID_X
"SELECT  sext." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + ", " +
"		se." + COLUMN_SOURCE_EXCERPT_ID + ", " +
"		se." + COLUMN_SOURCE_ID + ", " +
"		se." + COLUMN_SOURCE_EXCERPT_VALUE + ", " +
"		mt." + COLUMN_MEDIA_TAG_ID + ", " +
"		mt." + COLUMN_MEDIA_TAG_VALUE + " " +
"FROM " + TABLE_SOURCE_EXCERPT + " se " +
"LEFT JOIN " + TABLE_SOURCE_EXCERPT_TAGGING + " sext " +
"ON se." + COLUMN_SOURCE_EXCERPT_ID + " = sext." + COLUMN_SOURCE_EXCERPT_ID + " " +
"LEFT JOIN " + TABLE_MEDIA_TAG + " mt " +
"ON sext." + COLUMN_MEDIA_TAG_ID + " = mt." + COLUMN_MEDIA_TAG_ID + " " +
"WHERE se." + COLUMN_SOURCE_ID + " = ? " +
"AND IFNULL(sext." + COLUMN_SOURCE_EXCERPT_TAGGING_TAGGED_AT + ", '') >= IFNULL(sext." + COLUMN_SOURCE_EXCERPT_TAGGING_UNTAGGED_AT + ", ''); "

-- UPDATE_SOURCE_EXCERPT_TAGGING_TIMESTAMPS_X_Y_Z
"UPDATE " + TABLE_SOURCE_EXCERPT_TAGGING + "  " + 
"SET " + COLUMN_SOURCE_EXCERPT_TAGGING_TAGGED_AT + "  =  MAX(IFNULL(" + COLUMN_SOURCE_EXCERPT_TAGGING_TAGGED_AT + ", ''), ?), " + 
"	 " + COLUMN_SOURCE_EXCERPT_TAGGING_UNTAGGED_AT + " = MAX(IFNULL(" + COLUMN_SOURCE_EXCERPT_TAGGING_UNTAGGED_AT + ", ''), ?) " + 
"WHERE " + COLUMN_SOURCE_EXCERPT_TAGGING_ID + " = ? ; " 

-- UPDATE_SOURCE_TAG_WHERE_SOURCE_ID
"UPDATE " + TABLE_SOURCE + " " +
"SET " + COLUMN_SOURCE_TAG + " = ?  " +
"WHERE " + COLUMN_SOURCE_ID + " = ? ;  "

-- SELECT_SOURCE_EXCERPT_TAGGING_ID_X_Y
"SELECT " + COLUMN_SOURCE_EXCERPT_TAGGING_ID + " " + 
"FROM " + TABLE_SOURCE_EXCERPT_TAGGING + " " + 
"WHERE " + COLUMN_SOURCE_EXCERPT_ID + " = ?  " + 
"AND " + COLUMN_MEDIA_TAG_ID + " = ? ; "  

-- INSERT_OR_IGNORE_EXCERPT_TAGGING_X_Y
"INSERT OR IGNORE INTO " + TABLE_SOURCE_EXCERPT_TAGGING + " " +
"	(" + COLUMN_SOURCE_EXCERPT_ID + ", " + COLUMN_MEDIA_TAG_ID + ") " +
"VALUES " +
"	(?, ?); "

-- SELECT_EXCERPTS_WITH_SOURCE_FOR_TAG_ID_X
"SELECT sext." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + ", " + 
"		se." + COLUMN_SOURCE_EXCERPT_ID + ", " + 
"		se." + COLUMN_SOURCE_EXCERPT_VALUE + ", " + 
"		mt." + COLUMN_MEDIA_TAG_ID + ", " + 
"		mt." + COLUMN_MEDIA_TAG_VALUE + ", " + 
"		s." + COLUMN_SOURCE_ID + ", " + 
"		s." + COLUMN_SOURCE_AUTHOR + ", " + 
"		s." + COLUMN_SOURCE_TITLE + ", " + 
"		s." + COLUMN_SOURCE_URL + ", " + 
"		st." + COLUMN_SOURCE_TYPE_VALUE + " " + 
"FROM " + TABLE_SOURCE_EXCERPT + " se  " + 
"JOIN " + TABLE_SOURCE + " s " + 
"ON se." + COLUMN_SOURCE_ID + " = s." + COLUMN_SOURCE_ID + " " + 
"JOIN " + TABLE_SOURCE_TYPE + " st " + 
"ON s." + COLUMN_SOURCE_TYPE_ID + " = st." + COLUMN_SOURCE_TYPE_ID + " " + 
"LEFT JOIN " + TABLE_SOURCE_EXCERPT_TAGGING + " sext " + 
"ON se." + COLUMN_SOURCE_EXCERPT_ID + " = sext." + COLUMN_SOURCE_EXCERPT_ID + " " + 
"LEFT JOIN " + TABLE_MEDIA_TAG + " mt " + 
"ON sext." + COLUMN_MEDIA_TAG_ID + " = mt." + COLUMN_MEDIA_TAG_ID + " " + 
"WHERE sext." + COLUMN_SOURCE_EXCERPT_ID + " IN (SELECT " + COLUMN_SOURCE_EXCERPT_ID + " FROM " + TABLE_SOURCE_EXCERPT_TAGGING + " WHERE " + COLUMN_MEDIA_TAG_ID + " = ? ) " + 
"AND IFNULL(sext." + COLUMN_SOURCE_EXCERPT_TAGGING_TAGGED_AT + ", '') >= IFNULL(sext." + COLUMN_SOURCE_EXCERPT_TAGGING_UNTAGGED_AT + ", ''); "

-- SELECT_SOURCE_EXCERPT_BY_ID
"SELECT " + COLUMN_SOURCE_EXCERPT_ID + ", " +
"	    " + COLUMN_SOURCE_ID + ", " +
"	    " + COLUMN_SOURCE_EXCERPT_VALUE + ", " +
"	    " + COLUMN_SOURCE_EXCERPT_PAGES + ", " +
"	    " + COLUMN_SOURCE_EXCERPT_BEGIN_TIME + ", " +
"	    " + COLUMN_SOURCE_EXCERPT_END_TIME + " " +
"FROM " + TABLE_SOURCE_EXCERPT + "  " +
"WHERE " + COLUMN_SOURCE_EXCERPT_ID + " = ? ; "

-- SELECT_SOURCE_EXCERPT_ANNOTATIONS_BY_SOURCE_EXCERPT_ID
"SELECT sea." + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + ",  " +
"	    sea." + COLUMN_SOURCE_EXCERPT_ID + ",  " +
"	    sa." + COLUMN_SOURCE_ANNOTATION_ID + ",  " +
"	    sa." + COLUMN_SOURCE_ANNOTATION_VALUE + "  " +
"FROM " + TABLE_SOURCE_EXCERPT_ANNOTATION + " sea  " +
"JOIN " + TABLE_SOURCE_ANNOTATION + " sa  " +
"ON sea." + COLUMN_SOURCE_ANNOTATION_ID + " = sa." + COLUMN_SOURCE_ANNOTATION_ID + " " +
"WHERE sea." + COLUMN_SOURCE_EXCERPT_ID + " = ? ; " 

-- SELECT_SOURCE_ANNOTATION_ID_FOR_ANNOTATION_VALUE
"SELECT " + COLUMN_SOURCE_ANNOTATION_ID + " " +
"FROM " + TABLE_SOURCE_ANNOTATION + " " +
"WHERE " + COLUMN_SOURCE_ANNOTATION_VALUE + " = ? ; "

-- INSERT_OR_IGNORE_SOURCE_ANNOTATION_VALUE
"INSERT OR IGNORE INTO " + TABLE_SOURCE_ANNOTATION + " " + 
"	(" + COLUMN_SOURCE_ANNOTATION_VALUE + ") " + 
"VALUES " + 
"	(?) ; " 

-- INSERT_OR_IGNORE_SOURCE_EXCERPT_ANNOTATION_EXCERPT_ID_ANNOTATION_ID_X_Y
"INSERT OR IGNORE INTO " + TABLE_SOURCE_EXCERPT_ANNOTATION + " " + 
"	(" + COLUMN_SOURCE_EXCERPT_ID + ", " + 
"	 " + COLUMN_SOURCE_ANNOTATION_ID + ") " + 
"VALUES " + 
"	(?,?) ; " 

-- SELECT_LOCATION_ID_LOCATION_VALUE_FROM_SOURCE_TYPE
"SELECT " + COLUMN_SOURCE_LOCATION_ID + ", " +
"	    " + COLUMN_SOURCE_LOCATION_VALUE + " " +
"FROM " + TABLE_SOURCE_LOCATION + "; "

-- SELECT_SOURCE_LOCATION_ID_FOR_VALUE_X
"SELECT " + COLUMN_SOURCE_LOCATION_ID + " " +
"FROM " + TABLE_SOURCE_LOCATION + " " +
"WHERE " + COLUMN_SOURCE_LOCATION_VALUE + " = ? ; " 

-- INSERT_OR_IGNORE_SOURCE_LOCATION_VALUE
"INSERT OR IGNORE INTO " + TABLE_SOURCE_LOCATION + " " +
"	(" + COLUMN_SOURCE_LOCATION_VALUE + ") " +
"VALUES " +
"	(?); "

-- SELECT_SOURCE_LOCATION_SUBSETS_BY_LOCATION_ID_X
"SELECT " + COLUMN_SOURCE_LOCATION_SUBSET_ID + ", " + 
"	   " + COLUMN_SOURCE_LOCATION_ID + ", " + 
"	   " + COLUMN_SOURCE_LOCATION_SUBSET_VALUE + " " + 
"FROM " + TABLE_SOURCE_LOCATION_SUBSET + " " + 
"WHERE " + COLUMN_SOURCE_LOCATION_ID + " = ? ; " 

-- SELECT_SOURCE_LOCATION_SUBSET_ID_FOR_LOCATION_ID_AND_SUBSET_VALUE_X_Y
"SELECT " + COLUMN_SOURCE_LOCATION_SUBSET_ID + " " + 
"FROM " + TABLE_SOURCE_LOCATION_SUBSET + " " + 
"WHERE " + COLUMN_SOURCE_LOCATION_ID + " = ?  " + 
"AND " + COLUMN_SOURCE_LOCATION_SUBSET_VALUE + " = ? ; " 

-- INSERT_OR_IGNORE_SOURCE_LOCATION_SUBSET_FOR_LOCATION_ID_AND_SUBSET_VALUE_X_Y
"INSERT OR IGNORE INTO " + TABLE_SOURCE_LOCATION_SUBSET + "  " + 
"	(" + COLUMN_SOURCE_LOCATION_ID + ",  " + 
"	 " + COLUMN_SOURCE_LOCATION_SUBSET_VALUE + ") " + 
"VALUES  " + 
"	(?,?); " 


(above is copied just so SublimeText can use its autocomplete, remove after done)
------------------------------------------------------------------------------------------------------------------------------



-- CREATE_SOURCE_LOCATION
"CREATE TABLE " + TABLE_SOURCE_LOCATION + " ( " +
"	" + COLUMN_SOURCE_LOCATION_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_LOCATION_VALUE + " TEXT NOT NULL UNIQUE, " +
"	" + COLUMN_SOURCE_LOCATION_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_UPDATED_AT + " TEXT " +
") " 

-- CREATE_SOURCE_LOCATION_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_LOCATION + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_LOCATION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION + "." + COLUMN_SOURCE_LOCATION_ID + " = NEW." + COLUMN_SOURCE_LOCATION_ID + "; " +
"END " 

-- CREATE_SOURCE_LOCATION_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_LOCATION + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION + "." + COLUMN_SOURCE_LOCATION_ID + " = NEW." + COLUMN_SOURCE_LOCATION_ID + "; " +
"END " 







-- CREATE_SOURCE_ANNOTATION
"CREATE TABLE " + TABLE_SOURCE_ANNOTATION + " ( " +
"	" + COLUMN_SOURCE_ANNOTATION_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_ANNOTATION_VALUE + " TEXT NOT NULL UNIQUE, " +
"	" + COLUMN_SOURCE_ANNOTATION_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_ANNOTATION_UPDATED_AT + " TEXT " +
") " 

-- CREATE_SOURCE_ANNOTATION_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_ANNOTATION_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_ANNOTATION + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_ANNOTATION + "  " +
"	SET " + COLUMN_SOURCE_ANNOTATION_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_ANNOTATION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_ANNOTATION + "." + COLUMN_SOURCE_ANNOTATION_ID + " = NEW." + COLUMN_SOURCE_ANNOTATION_ID + "; " +
"END " 

-- CREATE_SOURCE_ANNOTATION_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_ANNOTATION_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_ANNOTATION + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_ANNOTATION + "  " +
"	SET " + COLUMN_SOURCE_ANNOTATION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_ANNOTATION + "." + COLUMN_SOURCE_ANNOTATION_ID + " = NEW." + COLUMN_SOURCE_ANNOTATION_ID + "; " +
"END " 






-- CREATE_SOURCE_TYPE
"CREATE TABLE " + TABLE_SOURCE_TYPE + " ( " +
"	" + COLUMN_SOURCE_TYPE_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_TYPE_VALUE + " TEXT NOT NULL UNIQUE, " +
"	" + COLUMN_SOURCE_TYPE_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_TYPE_UPDATED_AT + " TEXT " +
") " 

-- CREATE_SOURCE_TYPE_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_TYPE_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_TYPE + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_TYPE + "  " +
"	SET " + COLUMN_SOURCE_TYPE_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_TYPE_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_TYPE + "." + COLUMN_SOURCE_TYPE_ID + " = NEW." + COLUMN_SOURCE_TYPE_ID + "; " +
"END " 

-- CREATE_SOURCE_TYPE_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_TYPE_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_TYPE + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_TYPE + "  " +
"	SET " + COLUMN_SOURCE_TYPE_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_TYPE + "." + COLUMN_SOURCE_TYPE_ID + " = NEW." + COLUMN_SOURCE_TYPE_ID + "; " +
"END " 






-- CREATE_SOURCE
"CREATE TABLE " + TABLE_SOURCE + " ( " +
"	" + COLUMN_SOURCE_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_TYPE_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_TYPE + " (" + COLUMN_SOURCE_TYPE_ID + "), " +
"	" + COLUMN_SOURCE_AUTHOR + " TEXT, " +
"	" + COLUMN_SOURCE_DIRECTOR + " TEXT,  " +
"	" + COLUMN_SOURCE_TITLE + " TEXT,  " +
"	" + COLUMN_SOURCE_YEAR + " TEXT,  " +
"	" + COLUMN_SOURCE_URL + " TEXT,  " +
"	" + COLUMN_SOURCE_RETRIEVAL_DATE + " TEXT,  " +
"	" + COLUMN_SOURCE_TAG + " TEXT UNIQUE, " +
"	" + COLUMN_SOURCE_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_UPDATED_AT + " TEXT " +
") " 

-- CREATE_SOURCE_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE + "  " +
"	SET " + COLUMN_SOURCE_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE Source." + COLUMN_SOURCE_ID + " = NEW." + COLUMN_SOURCE_ID + "; " +
"END " 

-- CREATE_SOURCE_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE + "  " +
"	SET " + COLUMN_SOURCE_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE Source." + COLUMN_SOURCE_ID + " = NEW." + COLUMN_SOURCE_ID + "; " +
"END " 






-- CREATE_SOURCE_LOCATION_SUBSET
"CREATE TABLE " + TABLE_SOURCE_LOCATION_SUBSET + " ( " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_LOCATION_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_LOCATION + " (" + COLUMN_SOURCE_LOCATION_ID + "),  " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_VALUE + " TEXT NOT NULL, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_UPDATED_AT + " TEXT, " +
"	UNIQUE(" + COLUMN_SOURCE_LOCATION_ID + ", " + COLUMN_SOURCE_LOCATION_SUBSET_VALUE + ") " +
") " 

-- CREATE_SOURCE_LOCATION_SUBSET_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_SUBSET_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_LOCATION_SUBSET + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION_SUBSET + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_SUBSET_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_LOCATION_SUBSET_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION_SUBSET + "." + COLUMN_SOURCE_LOCATION_SUBSET_ID + " = NEW." + COLUMN_SOURCE_LOCATION_SUBSET_ID + "; " +
"END " 

-- CREATE_SOURCE_LOCATION_SUBSET_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_SUBSET_UPDATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_LOCATION_SUBSET + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION_SUBSET + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_SUBSET_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION_SUBSET + "." + COLUMN_SOURCE_LOCATION_SUBSET_ID + " = NEW." + COLUMN_SOURCE_LOCATION_SUBSET_ID + "; " +
"END " 






-- CREATE_SOURCE_LOCATION_SUBSET_ENTRY
"CREATE TABLE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + " ( " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_LOCATION_SUBSET + " (" + COLUMN_SOURCE_LOCATION_SUBSET_ID + "), " +
"	" + COLUMN_SOURCE_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE + " (" + COLUMN_SOURCE_ID + "),  " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_VALUE + " TEXT NOT NULL UNIQUE, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_VERIFIED_PRESENT_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_VERIFIED_MISSING_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_AT + " TEXT, " +
"	" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_UPDATED_AT + " TEXT, " +
"	UNIQUE(" + COLUMN_SOURCE_LOCATION_SUBSET_ID + ", " + COLUMN_SOURCE_ID + ", " + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_VALUE + ") " +
") " 

-- CREATE_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_AT + "  " +
"AFTER INSERT ON " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + "." + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + " = NEW." + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + "; " +
"END " 

-- CREATE_SOURCE_LOCATION_SUBSET_ENTRY_UPDATED_TRIGGER
"CREATE TRIGGER Set" + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_AT + " " +
"AFTER UPDATE ON " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + " " +
"BEGIN " +
"UPDATE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + "  " +
"	SET " + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_CREATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_SOURCE_LOCATION_SUBSET_ENTRY + "." + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + " = NEW." + COLUMN_SOURCE_LOCATION_SUBSET_ENTRY_ID + "; " +
"END " 






-- CREATE_SOURCE_EXCERPT
"CREATE TABLE " + TABLE_SOURCE_EXCERPT + " ( " + 
"	" + COLUMN_SOURCE_EXCERPT_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " + 
"	" + COLUMN_SOURCE_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE + " (" + COLUMN_SOURCE_ID + "), " + 
"	" + COLUMN_SOURCE_EXCERPT_VALUE + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_PAGES + " TEXT,  " + 
"	" + COLUMN_SOURCE_EXCERPT_BEGIN_TIME + " TEXT,  " + 
"	" + COLUMN_SOURCE_EXCERPT_END_TIME + " TEXT,  " + 
"	" + COLUMN_SOURCE_EXCERPT_CREATED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_UPDATED_AT + " TEXT " + 
") " 

-- CREATE_SOURCE_EXCERPT_CREATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_CREATED_AT + "  " + 
"AFTER INSERT ON " + TABLE_SOURCE_EXCERPT + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_CREATED_AT + " = CURRENT_TIMESTAMP,  " + 
"		   " + COLUMN_SOURCE_EXCERPT_UPDATED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT + "." + COLUMN_SOURCE_EXCERPT_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_ID + "; " + 
"END " 

-- CREATE_SOURCE_EXCERPT_UPDATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_UPDATED_AT + " " + 
"AFTER UPDATE ON " + TABLE_SOURCE_EXCERPT + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_UPDATED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT + "." + COLUMN_SOURCE_EXCERPT_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_ID + "; " + 
"END " 






-- CREATE_SOURCE_EXCERPT_ANNOTATION 
"CREATE TABLE " + TABLE_SOURCE_EXCERPT_ANNOTATION + " ( " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " + 
"	" + COLUMN_SOURCE_EXCERPT_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_EXCERPT + " (" + COLUMN_SOURCE_EXCERPT_ID + "),  " + 
"	" + COLUMN_SOURCE_ANNOTATION_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_ANNOTATION + " (" + COLUMN_SOURCE_ANNOTATION_ID + "), " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_LINKED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_UNLINKED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_CREATED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_ANNOTATION_UPDATED_AT + " TEXT,  " + 
"	UNIQUE(" + COLUMN_SOURCE_EXCERPT_ID + ", " + COLUMN_SOURCE_ANNOTATION_ID + ") " + 
") " 

-- CREATE_SOURCE_EXCERPT_ANNOTATION_CREATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_ANNOTATION_CREATED_AT + "  " + 
"AFTER INSERT ON " + TABLE_SOURCE_EXCERPT_ANNOTATION + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT_ANNOTATION + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_ANNOTATION_CREATED_AT + " = CURRENT_TIMESTAMP,  " + 
"		   " + COLUMN_SOURCE_EXCERPT_ANNOTATION_UPDATED_AT + " = CURRENT_TIMESTAMP, " + 
"		   " + COLUMN_SOURCE_EXCERPT_ANNOTATION_LINKED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT_ANNOTATION + "." + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + "; " + 
"END " 

-- CREATE_SOURCE_EXCERPT_ANNOTATION_UPDATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_ANNOTATION_UPDATED_AT + " " + 
"AFTER UPDATE ON " + TABLE_SOURCE_EXCERPT_ANNOTATION + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT_ANNOTATION + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_ANNOTATION_UPDATED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT_ANNOTATION + "." + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_ANNOTATION_ID + "; " + 
"END " 






-- CREATE_SOURCE_EXCERPT_TAGGING 
"CREATE TABLE " + TABLE_SOURCE_EXCERPT_TAGGING + " ( " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " + 
"	" + COLUMN_SOURCE_EXCERPT_ID + " INTEGER NOT NULL REFERENCES " + TABLE_SOURCE_EXCERPT + " (" + COLUMN_SOURCE_EXCERPT_ID + "),  " + 
"	" + COLUMN_MEDIA_TAG_ID + " INTEGER NOT NULL REFERENCES " + TABLE_MEDIA_TAG + " (" + COLUMN_MEDIA_TAG_ID + "), " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_TAGGED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_UNTAGGED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_CREATED_AT + " TEXT, " + 
"	" + COLUMN_SOURCE_EXCERPT_TAGGING_UPDATED_AT + " TEXT,  " + 
"	UNIQUE(" + COLUMN_SOURCE_EXCERPT_ID + ", " + COLUMN_MEDIA_TAG_ID + ") " + 
") " 

-- CREATE_SOURCE_EXCERPT_TAGGING_CREATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_TAGGING_CREATED_AT + "  " + 
"AFTER INSERT ON " + TABLE_SOURCE_EXCERPT_TAGGING + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT_TAGGING + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_TAGGING_CREATED_AT + " = CURRENT_TIMESTAMP,  " + 
"		   " + COLUMN_SOURCE_EXCERPT_TAGGING_UPDATED_AT + " = CURRENT_TIMESTAMP, " + 
"		   " + COLUMN_SOURCE_EXCERPT_TAGGING_TAGGED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT_TAGGING + "." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + "; " + 
"END " 

-- CREATE_SOURCE_EXCERPT_TAGGING_UPDATED_TRIGGER 
"CREATE TRIGGER Set" + COLUMN_SOURCE_EXCERPT_TAGGING_UPDATED_AT + " " + 
"AFTER UPDATE ON " + TABLE_SOURCE_EXCERPT_TAGGING + " " + 
"BEGIN " + 
"UPDATE " + TABLE_SOURCE_EXCERPT_TAGGING + "  " + 
"	SET " + COLUMN_SOURCE_EXCERPT_TAGGING_UPDATED_AT + " = CURRENT_TIMESTAMP " + 
"	WHERE " + TABLE_SOURCE_EXCERPT_TAGGING + "." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + " = NEW." + COLUMN_SOURCE_EXCERPT_TAGGING_ID + "; " + 
"END " 






