-- due to differences regarding sqlite, each of these
-- statements should be run by itself (one big statement fails)

-- table
"CREATE TABLE " + TABLE_MEDIA_TAGGING + " ( " +
"	" + COLUMN_MEDIA_TAGGING_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_MEDIA_ID + " INTEGER NOT NULL REFERENCES " + TABLE_MEDIA + " (" + COLUMN_MEDIA_ID + "),  " +
"	" + COLUMN_MEDIA_TAG_ID + " INTEGER NOT NULL REFERENCES " + TABLE_MEDIA_TAG + " (" + COLUMN_MEDIA_TAG_ID + "), " +
"	" + COLUMN_MEDIA_TAGGING_TAGGED_AT + " TEXT, " +
"	" + COLUMN_MEDIA_TAGGING_UNTAGGED_AT + " TEXT, " +
"	" + COLUMN_MEDIA_TAGGING_CREATED_AT + " TEXT, " +
"	" + COLUMN_MEDIA_TAGGING_UPDATED_AT + " TEXT,  " +
"	UNIQUE(" + COLUMN_MEDIA_ID + ", " + COLUMN_MEDIA_TAG_ID + ") " +
") " 

-- updated at trigger
"CREATE TRIGGER Set" + TABLE_MEDIA_TAGGING + "UpdatedAt " +
"AFTER UPDATE ON " + TABLE_MEDIA_TAGGING + " " +
"BEGIN " +
"UPDATE " + TABLE_MEDIA_TAGGING + "  " +
"	SET " + COLUMN_MEDIA_TAGGING_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_MEDIA_TAGGING + "." + COLUMN_MEDIA_TAGGING_ID + " = NEW." + COLUMN_MEDIA_TAGGING_ID + "; " +
"END " 

-- created at & updated at trigger
"CREATE TRIGGER Set" + TABLE_MEDIA_TAGGING + "CreatedAt  " +
"AFTER INSERT ON " + TABLE_MEDIA_TAGGING + " " +
"BEGIN " +
"UPDATE " + TABLE_MEDIA_TAGGING + "  " +
"	SET " + COLUMN_MEDIA_TAGGING_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_MEDIA_TAGGING_UPDATED_AT + " = CURRENT_TIMESTAMP, " +
"		   " + COLUMN_MEDIA_TAGGING_TAGGED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_MEDIA_TAGGING + "." + COLUMN_MEDIA_TAGGING_ID + " = NEW." + COLUMN_MEDIA_TAGGING_ID + "; " +
"END " 