-- due to differences regarding sqlite, each of these
-- statements should be run by itself (one big statement fails)

-- table
"CREATE TABLE " + TABLE_MEDIA_TRANSCRIPTION + " ( " +
"	" + COLUMN_MEDIA_TRANSCRIPTION_ID + " INTEGER NOT NULL PRIMARY KEY UNIQUE,  " +
"	" + COLUMN_MEDIA_ID + " INTEGER NOT NULL REFERENCES " + TABLE_MEDIA + " (" + COLUMN_MEDIA_ID + "),  " +
"	" + COLUMN_MEDIA_TRANSCRIPT_ID + " INTEGER NOT NULL REFERENCES " + TABLE_MEDIA_TRANSCRIPT + " (" + COLUMN_MEDIA_TRANSCRIPT_ID + "), " +
"	" + COLUMN_MEDIA_TRANSCRIPTION_CREATED_AT + " TEXT, " +
"	" + COLUMN_MEDIA_TRANSCRIPTION_UPDATED_AT + " TEXT,  " +
"	UNIQUE(" + COLUMN_MEDIA_ID + ", " + COLUMN_MEDIA_TRANSCRIPT_ID + ") " +
") " 

-- updated at trigger " +
"CREATE TRIGGER Set" + TABLE_MEDIA_TRANSCRIPTION + "UpdatedAt " +
"AFTER UPDATE ON " + TABLE_MEDIA_TRANSCRIPTION + " " +
"BEGIN " +
"UPDATE " + TABLE_MEDIA_TRANSCRIPTION + "  " +
"	SET " + COLUMN_MEDIA_TRANSCRIPTION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_MEDIA_TRANSCRIPTION + "." + COLUMN_MEDIA_TRANSCRIPTION_ID + " = NEW." + COLUMN_MEDIA_TRANSCRIPTION_ID + "; " +
"END "

-- created at & updated at trigger " +
"CREATE TRIGGER Set" + TABLE_MEDIA_TRANSCRIPTION + "CreatedAt  " +
"AFTER INSERT ON " + TABLE_MEDIA_TRANSCRIPTION + " " +
"BEGIN " +
"UPDATE " + TABLE_MEDIA_TRANSCRIPTION + "  " +
"	SET " + COLUMN_MEDIA_TRANSCRIPTION_CREATED_AT + " = CURRENT_TIMESTAMP,  " +
"		   " + COLUMN_MEDIA_TRANSCRIPTION_UPDATED_AT + " = CURRENT_TIMESTAMP " +
"	WHERE " + TABLE_MEDIA_TRANSCRIPTION + "." + COLUMN_MEDIA_TRANSCRIPTION_ID + " = NEW." + COLUMN_MEDIA_TRANSCRIPTION_ID + "; " +
"END " 