
"ALTER TABLE " + TABLE_MEDIA_DEVICE_PATH + " ADD COLUMN " + COLUMN_MEDIA_DEVICE_PATH_VERIFIED_PRESENT + " TEXT; "
"ALTER TABLE " + TABLE_MEDIA_DEVICE_PATH + " ADD COLUMN " + COLUMN_MEDIA_DEVICE_PATH_VERIFIED_MISSING + " TEXT; "

TABLE_MEDIA_DEVICE_PATH
COLUMN_MEDIA_DEVICE_PATH_VERIFIED_PRESENT
COLUMN_MEDIA_DEVICE_PATH_VERIFIED_MISSING

public static final String COLUMN_MEDIA_DEVICE_PATH_VERIFIED_PRESENT = "ColumnMediaDevicePathVerifiedPresent";
public static final String COLUMN_MEDIA_DEVICE_PATH_VERIFIED_MISSING = "ColumnMediaDevicePathVerifiedMissing";