-- STUDIO_V5_INSERT_CHORD_PROGRESSION_SIGNATURE_NOTES_X_Y
"INSERT OR IGNORE INTO " + TABLE_CHORD_PROGRESSION + "  "
 + "	(" + COLUMN_CHORD_PROGRESSION_SIGNATURE + ", "
 + "	 " + COLUMN_CHORD_PROGRESSION_NOTES + ") "
 + "VALUES "
 + "	(?, ?) ; "
 
 -- Signature is UNIQUE, and once in we don't wanna change it, so keyed on sig. 
 -- STUDIO_V5_UPDATE_CHORD_PROGRESSION_NOTES_BY_SIGNATURE_X_Y 
 "UPDATE " + TABLE_CHORD_PROGRESSION + " "
 + "SET " + COLUMN_CHORD_PROGRESSION_NOTES + " = ? "
 + "WHERE " + COLUMN_CHORD_PROGRESSION_SIGNATURE + " = ? ; "
 
 -- STUDIO_V5_SELECT_ALL_CHORD_PROGRESSIONS_ID_SIGNATURE_NOTES 
 "SELECT " + COLUMN_CHORD_PROGRESSION_ID + ", "
 + "	   " + COLUMN_CHORD_PROGRESSION_SIGNATURE + ", "
 + "	   " + COLUMN_CHORD_PROGRESSION_NOTES + " "
 + "FROM " + TABLE_CHORD_PROGRESSION + " ; "
 
 -- STUDIO_V5_SELECT_CHORD_PROGRESSION_BY_SIGNATURE_X 
 "SELECT " + COLUMN_CHORD_PROGRESSION_ID + ", "
 + "	   " + COLUMN_CHORD_PROGRESSION_SIGNATURE + ", "
 + "	   " + COLUMN_CHORD_PROGRESSION_NOTES + " "
 + "FROM " + TABLE_CHORD_PROGRESSION + " "
 + "WHERE " + COLUMN_CHORD_PROGRESSION_SIGNATURE + " = ? ; " + 